name: CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-qa:
    runs-on: aws-ec2 # Use appropriate OS
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull scrum-master-user-managment Image from Docker Hub
        run: docker pull radhikaschude/scrummasterusermanagment:latest

      - name: Stop and Remove Old scrum-master-user-managment Container
        run: |
          docker stop scrum-master-user-managment-container || true
          docker rm scrum-master-user-managment-container || true

      - name: Run Docker Container for scrum-master-user-managment
        run: |
          docker run -d -p 8081:8081 --restart unless-stopped --name scrum-master-user-managment-container radhikaschude/scrummasterusermanagment:latest

# same for all repo
      - name: Pull spring-security-test Image from Docker Hub
        run: docker pull radhikaschude/spring-security-test:latest

      - name: Stop and Remove Old spring-security-test Container
        run: |
          docker stop spring-security-test-container || true
          docker rm spring-security-test-container || true

      - name: Run Docker Container for spring-security-test
        run: |
          docker run -d -p 8082:8082 --restart unless-stopped --name spring-security-test-container radhikaschude/spring-security-test:latest    

#eureka
      - name: Pull eureka-server Image from Docker Hub
        run: docker pull radhikaschude/eureka-server:latest

      - name: Stop and Remove Old eureka-server Container 
        run: |
          docker stop eureka-server-container || true
          docker rm eureka-server-container || true

      - name: Run Docker Container for eureka-server
        run: |
          docker run -d -p 8761:8761 --restart unless-stopped --name eureka-server-container radhikaschude/eureka-server:latest          
